CREATE TABLE NOTE_TAGS
(
  ID       NUMBER,
  NOTE_ID  NUMBER                               NOT NULL,
  TAG      VARCHAR2(255 BYTE)                   NOT NULL,
  CONSTRAINT NOTES_TAGS_PK
 PRIMARY KEY
 (ID),
  CONSTRAINT FK_NOTE_TAGS_NOTE 
 FOREIGN KEY (NOTE_ID) 
 REFERENCES NOTES (ID)
 ON DELETE CASCADE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;




