CREATE TABLE NOTES
(
  ID     NUMBER,
  NOTEBOOK_ID NUMBER,
  TITLE  VARCHAR2(250 BYTE)                     NOT NULL,
  NOTE   VARCHAR2(4000 BYTE)                    NOT NULL,
  CREATED_AT DATE NOT NULL,
  CREATED_BY VARCHAR2( 40 ) NOT NULL,
  UPDATED_AT DATE NOT NULL,
  UPDATED_BY VARCHAR2( 40 ) NOT NULL,
  CONSTRAINT NOTES_PK
 PRIMARY KEY
 (ID),
  CONSTRAINT FK_NOTES_NOTEBOOK_ID
  FOREIGN KEY
  (NOTEBOOK_ID) REFERENCES NOTEBOOKS(ID)    
  ON DELETE CASCADE    
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;




