CREATE TABLE NOTE_COMMENTS
(
  ID          NUMBER,
  NOTE_ID     NUMBER                            NOT NULL,
  TEXT        VARCHAR2(4000 BYTE)               NOT NULL,
  CREATED_AT  DATE                              NOT NULL,
  CREATED_BY  VARCHAR2(40 BYTE)                 NOT NULL,
  UPDATED_AT  DATE                              NOT NULL,
  UPDATED_BY  VARCHAR2( 40 BYTE)                NOT NULL,
  CONSTRAINT NOTE_COMMENTS_PK
 PRIMARY KEY
 (ID),
  CONSTRAINT NOTE_COMMENTS_NOTE_FK
  FOREIGN KEY (NOTE_ID) REFERENCES NOTES(ID) ON DELETE CASCADE    
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;




