require "oci8"
require "highline/import"
require "orasaurus"

$db_name = ""
$db_user = ""
$db_user_password = ""

def process_db_connect_params
	
	if ENV['db_user'].nil? then
	  $db_user = ask("Database User:  ") { |q| q.echo = true }	  
	else
		$db_user = ENV['db_user']
	end
	
	if ENV['db_user_password'].nil? then
	  $db_user_password = ask("Database User Password:  ") { |q| q.echo = "*" }	  
	else
		$db_user_password = ENV['db_user_password']
	end
	
	if ENV['db_name'].nil? then
		$db_name = ask("Database Instance:  ") { |q| q.echo = true }	  
	else
	  $db_name = ENV['db_name']	  
	end	
	
	if not $db_user.nil? and not $db_user_password.nil? and not $db_name.nil? then
	  return true
	else
	  puts "INVALID DATABASE CONNECTION PARAMETERS"
	end
	
end

def sqlplus_connect_string
	return $db_user + "/" + $db_user_password + "@" + $db_name
end

desc "Test database connection"
task :test_connection do
	if not process_db_connect_params then
		exit
		puts "test failed"
	else
	  puts "valid parameters"
	end	
	puts "Starting database connection test"
	begin
		conn = OCI8.new( $db_user, $db_user_password, $db_name )
		conn.logoff
		puts "Connection successful"
	rescue
		puts $!
		puts "Connection failed"
	end
end

desc "Rebuild all build and teardown scripts"
task :rebuild_build_scripts do
	if not process_db_connect_params then
		exit
	end
  
  s = Orasaurus::ScriptBuilder.new( '.' )
  puts "building simple build scripts"
  s.build_all_scripts( 'build.sql', 'teardown.sql' )

  #puts "re-doing table build scripts for proper order"
  #t = Orasaurus::TableScriptBuilder.new( $db_user, $db_user_password, $db_name, './Tables/' )
  #puts 'build_tables has finished'
  
  puts 'done' 
end