CREATE TABLE NOTEBOOKS
(
  ID     NUMBER,
  TITLE  VARCHAR2(255 BYTE)                     NOT NULL,
  CONSTRAINT NOTEBOOKS_PK
 PRIMARY KEY
 (ID)
    USING INDEX 
    TABLESPACE LARGE_TABLES,
  CONSTRAINT UNIQ_NOTEBOOK_TITLE
 UNIQUE (TITLE)
    USING INDEX 
    TABLESPACE LARGE_TABLES
)
TABLESPACE LARGE_TABLES
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;






